config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :videos, only: [:index, :show] do
    member do
      post :collect
      post :discollect
    end
    resources :reviews
  end

  namespace :account do
    resources :favorites
    resources :reviews
  end

  root "videos#index"
  get 'pages/contact'

  namespace :admin do
    resources :videos
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :video
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :video
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :favorites
  has_many :favorite_videos, through: :favorites, source: :video

  has_many :reviews

  def admin?
    is_admin
  end

  def favorites?(video)
    favorite_videos.include?(video)
  end

  def collect!(video)
    favorite_videos << video
  end

  def discollect!(video)
    favorite_videos.delete(video)
  end
end

app/models/video.rb
class Video < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :favorites
  has_many :collectors, through: :favorites, source: :user

  has_many :reviews

  def next
    Video.where("id > ?", id).first
  end

  def prev
    Video.where("id < ?", id).last
  end

end

app/controllers/account/favorites_controller.rb
class Account::FavoritesController < ApplicationController
  before_action :authenticate_user!

  def index
    @videos = current_user.favorite_videos
  end
end

app/controllers/account/reviews_controller.rb
class Account::ReviewsController < ApplicationController
  before_action :authenticate_user!

  def index
    @reviews = current_user.reviews
  end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_required

  def index
    @videos = Video.all
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    if @video.save
      redirect_to admin_videos_path
    else
      render :new
    end
  end

  def edit
    @video = Video.find_by(id: params[:id])
  end

  def update
    @video = Video.find_by(id: params[:id])
    if @video.update(video_params)
      redirect_to admin_videos_path
    else
      render :edit
    end
  end

  def destroy
    @video = Video.find_by(params[:id])
    @video.destroy
    redirect_to admin_videos_path
  end

  private

  def video_params
    params.require(:video).permit(:wistia, :description, :title, :image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def admin_required
    if !current_user.admin?
      redirect_to videos_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    @video = Video.find_by(id: params[:video_id])
    @review = @video.reviews.new(review_params)
    @review.video = @video
    @review.user = current_user

    if @review.save
      redirect_to video_path(@video)
    end
  end

  def destroy
    @video = Video.find_by(id: params[:video_id])
    @review = Review.find_by(id: params[:id])
    @review.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!, only: [:show, :collect, :discollect]

  def index
    @videos = Video.all
    @video = Video.find_by(id: params[:id])

    render layout: "rootnavbar"
  end

  def show
    @videos = Video.all
    @video = Video.find_by(id: params[:id])

    @next_video = @video.next
    @prev_video = @video.prev

  end

  def collect
    @video = Video.find_by(id: params[:id])
    if !current_user.favorites?(@video)
      current_user.collect!(@video)
    end
    redirect_back fallback_location: root_path
  end

  def discollect
    @video = Video.find_by(id: params[:id])
    if current_user.favorites?(@video)
      current_user.discollect!(@video)
    end
    redirect_back fallback_location: root_path
  end
end

app/helpers/account/favorites_helper.rb
module Account::FavoritesHelper
end

app/helpers/account/reviews_helper.rb
module Account::ReviewsHelper
end

app/helpers/admin/videos_helper.rb
module Admin::VideosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/admin/videos/_form.html.erb
<%= form_for [:admin, @video] do |f| %>
  <div class="input-field">
    <%= f.text_field :wistia, placeholder: 'Link', length: '10' %>
  </div>

  <div class="input-field">
    <%= f.text_field :title, placeholder: 'Title', length: '20' %>
  </div>

  <div class="input-field">
    <%= f.text_area :description, placeholder: 'Description', length: '800', class: 'materialize-textarea'  %>
  </div>

  <% if @video.image.present? %>
    <span>Video Image</span><br>
    <%= image_tag(@video.image.thumb.url) %>
  <% end %>
  <div class="file-field input-field col s12">
    <div class="btn-flat img-button col m1">
      <span><i class="material-icons large" style="font-size: 3rem;">cloud_upload</i></span>
      <%= f.file_field :image, as: :file %>
    </div>
    <div class="file-path-wrapper col m11">
      <%= text_field_tag nil, (f.object.image unless f.object.image.blank?), {id: nil, class: 'file-path validate', placeholder: 'Your filename here!', style: 'margin-left: 0px;width: 40%;'} %>
    </div>
  </div>

  <div class="col m12" style="margin-bottom: 20px;">
    <button type="submit" name="button" class="btn waves-effect waves-light">Submit</button>
    <a href="<%= admin_videos_path %>" class="btn waves-effect waves-light">Back</a>
  </div>

<% end %>

app/views/admin/videos/edit.html.erb
<h1>Edit Video</h1>

<div class="card">
  <div class="card-content">

    <%= form_for [:admin, @video] do |f| %>
      <div class="input-field">
        <%= f.text_field :wistia, placeholder: 'Link', length: '10' %>
      </div>

      <div class="input-field">
        <%= f.text_field :title, placeholder: 'Title', length: '20' %>
      </div>

      <div class="input-field">
        <%= f.text_area :description, placeholder: 'Description', length: '800', class: 'materialize-textarea'  %>
      </div>

      <% if @video.image.present? %>
        <span>Video Image</span><br>
        <%= image_tag(@video.image.thumb.url) %>
      <% end %>
      <div class="file-field input-field col s12">
        <div class="btn-flat img-button col m1">
          <span><i class="material-icons large" style="font-size: 3rem;">cloud_upload</i></span>
          <%= f.file_field :image, as: :file %>
        </div>
        <div class="file-path-wrapper col m11">
          <%= text_field_tag nil, (f.object.image unless f.object.image.blank?), {id: nil, class: 'file-path validate', placeholder: 'Your filename here!', style: 'margin-left: 0px;width: 40%;'} %>
        </div>
      </div>

      <div class="col m12" style="margin-bottom: 20px;">
        <button type="submit" name="button" class="btn waves-effect waves-light">Submit</button>
        <a href="<%= admin_videos_path %>" class="btn waves-effect waves-light">Back</a>
      </div>

    <% end %>

  </div>
</div>

app/views/admin/videos/index.html.erb
<h1>Video</h1>

<%= link_to new_admin_video_path, class: "btn-floating btn-large waves-effect waves-light blue" do %>
  <i class="mdi-content-add"></i>
<% end %>

<table>
  <thead>
    <tr>
      <th>Wistia</th>
      <th>Title</th>
      <th>description</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= link_to video.wistia, video %></td>
        <td><%= video.title %></td>
        <td><%= video.description %></td>
        <td><%= link_to "Edit", edit_admin_video_path(video) %></td>
        <td><%= link_to "Destroy", admin_video_path(video), method: :delete, data: { confirm: "Are you sure?"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/videos/new.html.erb
<h1>New Video</h1>

<div class="card">
  <div class="card-content">

    <%= form_for [:admin, @video] do |f| %>
      <div class="input-field">
        <%= f.text_field :wistia, placeholder: 'Link', length: '10' %>
      </div>

      <div class="input-field">
        <%= f.text_field :title, placeholder: 'Title', length: '20' %>
      </div>

      <div class="input-field">
        <%= f.text_area :description, placeholder: 'Description', length: '800', class: 'materialize-textarea'  %>
      </div>

      <div class="file-field input-field col s12">
        <div class="btn-flat img-button col m1">
          <span><i class="material-icons large" style="font-size: 3rem;">cloud_upload</i></span>
          <%= f.file_field :image, as: :file %>
        </div>
        <div class="file-path-wrapper col m11">
          <%= text_field_tag nil, (f.object.image.original_filename unless f.object.image.blank?), {id: nil, class: 'file-path validate', placeholder: 'Your filename here!', style: 'margin-left: 0px;width: 40%;'} %>
        </div>
      </div>

      <button type="submit" name="button" class="btn waves-effect waves-light">Submit</button>
      <a href="<%= admin_videos_path %>" class="btn waves-effect waves-light">Back</a>
    <% end %>


  </div>
</div>

app/views/common/_navbar.html.erb
<div class="navbar-fixed">
  <nav id="navbar">
    <div class="nav-wrapper">
      <a href="<%= videos_path %>" class="brand-logo" style="padding-left: 40px;">VideosPlace</a>
      <ul class="right hide-on-med-and-down">

        <li><a href="<%= pages_contact_path %>"><i class="mdi-maps-place"></i></a></li>
      </ul>

      <ul class="side-nav" id="mobile-demo">
        <% if !current_user %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% else %>
          <li>
            <a class="dropdown-button" href="#!" data-activates="dropdown1">
              Hi, <%= current_user.email %>
              <i class="material-icons right">arrow_drop_down</i>
            </a>

            <!-- Dropdown Structure -->
            <ul id="dropdown1" class="dropdown-content">
              <li><a href="<%= pages_contact_path %>"><i class="mdi-maps-place"></i></a></li>
              <% if current_user.admin? %>
                <li><%= link_to("Admin Panel", admin_videos_path) %></li>
              <% end %>
              <li><%= link_to "My Favorites", account_favorites_path %></li>
              <li><%= link_to "My Reviews", account_reviews_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>

          </li>
        <% end %>


      </ul>
    </div>
  </nav>
</div>

<script>
  $(document).ready(function(){
    $('.dropdown-button').dropdown({
      // dropdown-content從按鈕下開始
      belowOrigin: true
    });
  });
</script>

app/views/common/_rootnavbar.html.erb
<style>
#rootnavbar{
  background: transparent;
  height: 0;
  color: #00C1F9;
}
#rootnavbar .brand-logo{
  color: #00C1F9;
  font-family: 'Lobster';
}
#rootnavbar ul a {
  color: #00C1F9;
}
#rootnavbar.index_navbar_bgcolor {
  background: #fff;
  height: auto;
}
</style>

<div class="navbar-fixed">
  <nav id="rootnavbar">
    <div class="nav-wrapper">
      <a href="<%= videos_path %>" class="brand-logo" style="padding-left: 40px;">VideosPlace</a>
      <ul class="right hide-on-med-and-down">
        <!-- <li><a href="sass.html">Sass</a></li>
        <li><a href="badges.html">Components</a></li> -->
        <!-- Dropdown Trigger -->
        <li><a href="<%= pages_contact_path %>"><i class="mdi-maps-place"></i></a></li>
        <% if !current_user %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% else %>
          <li>
            <a class="dropdown-button" href="#!" data-activates="dropdown1">
              Hi, <%= current_user.email %>
              <i class="material-icons right">arrow_drop_down</i>
            </a>

            <!-- Dropdown Structure -->
            <ul id="dropdown1" class="dropdown-content">
              <% if current_user.admin? %>
                <li><%= link_to("Admin Panel", admin_videos_path) %></li>
              <% end %>
              <li><%= link_to "My Favorites", account_favorites_path %></li>
              <li><%= link_to "My Reviews", account_reviews_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>

          </li>
        <% end %>

      </ul>
    </div>
  </nav>
</div>

<script>
  $(document).ready(function(){
    $('.dropdown-button').dropdown({
      // dropdown-content從按鈕下開始
      belowOrigin: true
    });
    $(window).scroll(function(){
      if($(this).scrollTop() > 420){
        $('#rootnavbar').addClass('index_navbar_bgcolor')
      }else {
        $('#rootnavbar').removeClass('index_navbar_bgcolor')
      }
    })
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideosPlace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/css/materialize.min.css">

    <!-- Icon -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!--Google Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bungee" rel="stylesheet">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/js/materialize.min.js"></script>

  </head>

  <body>
    <%= render "common/navbar" %>
    <div class="row">
      <div class="col m10 offset-m1">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/rootnavbar.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideosPlace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/css/materialize.min.css">

    <!-- Icon -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!--Google Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/js/materialize.min.js"></script>

  </head>

  <body>
    <%= render "common/rootnavbar" %>
    <div class="row">
      <div class="col m10 offset-m1">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pages/contact.html.erb
<h3>Contact</h3>

<div class="card z-depth-3">
  <div class="card-content">
    <p>Find me on the map!</p>
    <br/>
		<div id="map-canvas"></div>
  </div>
</div>

<style>
  #map-canvas {
    width: 100%;
    height: 400px;
  }
</style>

<script src="https://maps.googleapis.com/maps/api/js"></script>
<script>
  function initialize() {
    var mapCanvas = document.getElementById('map-canvas');
    var mapOptions = {
      center: new google.maps.LatLng(25.030176, 121.472489),
      zoom: 14,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }
    var map = new google.maps.Map(mapCanvas, mapOptions);
    var marker = new google.maps.Marker({
    	position: new google.maps.LatLng(25.030176, 121.472489),
    	title: "Here is Me!"
    });
    marker.setMap(map);
  }
  google.maps.event.addDomListener(window, 'load', initialize);
</script>

<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDcZtMN80zsjEdUmsl4twY6HL7vTSn0e4I&callback=initMap"   type="text/javascript"></script>

app/views/reviews/_form.html.erb
<%= form_for [@video, @video.reviews.build] do |f|%>

  <div class="input-field">
      <%= f.text_area :content, class: "form-control" %>
  </div>
 <br>
  <div class="reviews-form">
    <%= f.submit "Add a Review", class: "btn btn-primary pull-right light-blue darken-2" %>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<div class="pull-left">
    <p ><%= review.content %></p>
</div>
<br>
<div class="pull-right">
    <p>
        <small>Submitted
            <strong>
              <%= time_ago_in_words(review.created_at) %>ago
            </strong>
            by
            <%= review.user.email %></small>
    </p>
</div>
<br>

  <div class="review-delete review-delete-showpage">
  <% if review.user == current_user %>
    <%= link_to video_review_path(review.video, review), class: "btn btn-floating pulse delete-favorite right", method: :delete, data: { confirm: "Are you sure?"} do %>
      <i class="material-icons small">delete</i>
    <% end %>
  <% end %>

  <br>
  <hr style="margin-top: 20px;">

  </div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/videos/index.html.erb
<div class="container" style="height: 90vh;">
  <iframe src="https://www.youtube.com/embed/IM_z4XJbSFM?ecver=1&controls=0&showinfo=0&rel=0&loop=1&mute=1&autoplay=1&playlist=IM_z4XJbSFM" frameborder="0" allowfullscreen></iframe>
</div>

<h1 style="text-align: center;" class="video_index">Video Index</h1>

<div class="row">
  <% @videos.each do |video| %>
  <div class="col s12 m4">
    <div class="card light-blue darken-4 darken-1">
      <div class="card-image">
        <%= link_to video_path(video) do %>
          <% if video.image.present? %>
            <%= image_tag(video.image.thumb.url, class: "thumbnail") %>
          <% else %>
            <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
          <% end %>
        <% end %>
      </div>
      <div class="card-action">
        <%= link_to video.title, video_path(video) %>

        <% if current_user && current_user.favorites?(video) %>
          <%= link_to discollect_video_path(video), class: "right", method: :post do %>
            <i class="material-icons small love-color">favorite</i>
          <% end %>
        <% else %>
          <%= link_to collect_video_path(video), class: "right", method: :post do %>
            <i class="material-icons small love-color-change">favorite_border</i>
          <% end %>
        <% end %>

      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/videos/show.html.erb
<div class="row" style="margin-top: 15px;">
  <div class="col m3">
    <div class="collection">
      <% @videos.each do |video| %>
        <%= link_to video.title, video_path(video), class: "collection-item light-blue-text text-darken-4" %>
      <% end %>
    </div>
  </div>
  <div class="col m9">
    <div class="card light-blue darken-4 darken-1">
      <div class="card-image">
        <div id="wistia_<%= @video.wistia %>"></div>
      </div>
      <div class="card-content white-text">
        <button class="btn btn-primary light-blue darken-1" onclick="setPlaySpeed(0.75)">0.75x</button>
        <button class="btn btn-primary light-blue darken-1" onclick="setPlaySpeed(1)">1x</button>
        <button class="btn btn-primary light-blue darken-1" onclick="setPlaySpeed(1.25)">1.25x</button>
        <button class="btn btn-primary light-blue darken-1" onclick="setPlaySpeed(1.5)">1.5x</button>
        <button class="btn btn-primary light-blue darken-1" onclick="setPlaySpeed(2)">2x</button>

        <% if current_user && current_user.favorites?(@video) %>
          <%= link_to discollect_video_path(@video), class: "right", method: :post do %>
            <i class="material-icons small love-color">favorite</i>
          <% end %>
        <% else %>
          <%= link_to collect_video_path(@video), class: "right", method: :post do %>
            <i class="material-icons small love-color-change">favorite_border</i>
          <% end %>
        <% end %>

        <div class="row">
        <div class="col s12" style="margin-bottom: 10px;">
          <ul class="tabs light-blue darken-4">
            <li class="tab col s4"><a href="#test1">Title</a></li>
            <li class="tab col s4"><a href="#test2">Description</a></li>
            <li class="tab col s4"><a href="#test3" class="active">Reviews ( <%= @video.reviews.count %> )</a></li>
          </ul>
        </div>
        <div id="test1" class="col s12"><%= @video.title %></div>
        <div id="test2" class="col s12"><%= @video.description %></div>
        <div id="test3" class="col s12">
          <%= render @video.reviews %>

          <%= render "reviews/form" %>
        </div>
      </div>

      </div>
      <div class="card-action" style="height: 60px;">
        <%= link_to "Previous", @prev_video if !@prev_video.nil? %>
        <span class="right">
          <%= link_to "Next", @next_video if !@next_video.nil? %>
        </span>
      </div>
    </div>
  </div>
</div>

<script src="https://fast.wistia.net/static/E-v1.js"></script>
<script>
  wistiaEmbed = Wistia.embed('<%= @video.wistia %>', {
    videoQuality: 'hd-only',
    videoFoam: true
  });

  function setPlaySpeed(speed) {
    wistiaEmbed.playbackRate(speed);
  }
</script>